services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    user: "1000:1000"
    network_mode: host

    environment:
      - TZ=Europe/Warsaw
      - JELLYFIN_PublishedServerUrl=http://jellyfin.local

    volumes:
      - /opt/homelab/config/jellyfin/config:/config
      - /opt/homelab/config/jellyfin/cache:/cache
      - /opt/homelab/config/jellyfin/fonts:/usr/local/share/fonts/custom:ro
      - /mnt/media:/media

    extra_hosts:
      - host.docker.internal:host-gateway

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped

    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
      - WEBUI_PORT=8080

    volumes:
      - /opt/homelab/config/qbittorrent:/config
      - /mnt/media:/media

    ports:
      - "8080:8080"
      - "6881:6881"
      - "6881:6881/udp"
  
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr

    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw

    volumes:
      - /opt/homelab/config/prowlarr:/config

    ports:
      - "9696:9696"

    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr

    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw

    volumes:
      - /opt/homelab/config/radarr:/config
      - /mnt/media:/media

    ports:
      - "7878:7878"

    restart: unless-stopped

   bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr

    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw

    volumes:
      - /opt/homelab/config/bazarr:/config
      - /mnt/media:/media

    ports:
      - "6767:6767"

    restart: unless-stopped
